version: '3.8'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3388:3306"
    environment:
      MYSQL_DATABASE: like_app
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
